services:
  app:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/app
  postgres:
    image: postgres
    # ports:
    # - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - './db:/var/lib/postgresql/data/pgdata'
